apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pdf-currency-blur-minimal
  annotations:
    scenarios.ai.sap.com/description: "PDF Currency Blur Microservice - Minimal"
    scenarios.ai.sap.com/name: "PDF Processing Minimal"
    executables.ai.sap.com/description: "Simple PDF currency blur service"
    executables.ai.sap.com/name: "PDF Blur Minimal"
  labels:
    scenarios.ai.sap.com/id: "pdf-processing"
    ai.sap.com/version: "2.0.0"
spec:
  entrypoint: serve-model
  templates:
  - name: serve-model
    metadata:
      labels:
        ai.sap.com/resourcePlan: "infer.s"
    steps:
    - - name: deploy-service
        template: pdf-currency-blur-deployment

  - name: pdf-currency-blur-deployment
    metadata:
      labels:
        ai.sap.com/resourcePlan: "infer.s"
    resource:
      action: apply
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: pdf-currency-blur
          labels:
            ai.sap.com/resourcePlan: "infer.s"
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: pdf-currency-blur
          template:
            metadata:
              labels:
                app: pdf-currency-blur
                ai.sap.com/resourcePlan: "infer.s"
            spec:
              containers:
              - name: inference
                image: "acastropardo/pdf-currency-blur-iacore:latest"
                ports:
                - containerPort: 8080
                env:
                - name: PORT
                  value: "8080"
                resources:
                  requests:
                    memory: "1Gi"
                    cpu: "500m"
                  limits:
                    memory: "2Gi"
                    cpu: "1000m"
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: pdf-currency-blur-service
          labels:
            ai.sap.com/resourcePlan: "infer.s"
        spec:
          selector:
            app: pdf-currency-blur
          ports:
          - port: 8080
            targetPort: 8080
            protocol: TCP
          type: ClusterIP
