apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pdf-currency-blur-basic
  annotations:
    scenarios.ai.sap.com/description: "PDF Currency Blur Test"
    scenarios.ai.sap.com/name: "PDF Test"
    executables.ai.sap.com/description: "Basic test service"
    executables.ai.sap.com/name: "PDF Test Basic"
  labels:
    scenarios.ai.sap.com/id: "pdf-processing"
    ai.sap.com/version: "2.0.0"
spec:
  entrypoint: test-container
  templates:
  - name: test-container
    container:
      image: "docker.io/python:3.9-slim"
      command: ["python"]
      args: ["-c", "print('Hello from SAP AI Core'); import time; time.sleep(30)"]
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "100m"
