apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pdf-currency-blur-minimal
  labels:
    scenarios.ai.sap.com/id: "pdf-processing"
    ai.sap.com/version: "2.0.0"
spec:
  template: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: pdf-currency-blur\n  labels:\n    ai.sap.com/resourcePlan: infer.s\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: pdf-currency-blur\n  template:\n    metadata:\n      labels:\n        app: pdf-currency-blur\n        ai.sap.com/resourcePlan: infer.s\n    spec:\n      containers:\n        - name: inference\n          image: acastropardo/pdf-currency-blur-iacore:latest\n          ports:\n            - containerPort: 8080\n          env:\n            - name: PORT\n              value: '8080'\n          resources:\n            requests:\n              memory: 3Gi\n              cpu: 1500m\n            limits:\n              memory: 6Gi\n              cpu: 3000m"
