apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pdf-currency-blur-minimal
  annotations:
    scenarios.ai.sap.com/description: "PDF Currency Blur Microservice - Minimal"
    scenarios.ai.sap.com/name: "PDF Processing Minimal"
    executables.ai.sap.com/description: "Simple PDF currency blur service"
    executables.ai.sap.com/name: "PDF Blur Minimal"
  labels:
    scenarios.ai.sap.com/id: "pdf-processing"
    ai.sap.com/version: "2.0.0"
spec:
  entrypoint: serve-model
  templates:
  - name: serve-model
    metadata:
      labels:
        ai.sap.com/resourcePlan: "infer.s"
    container:
      image: "acastropardo/pdf-currency-blur-iacore:latest"
      ports:
        - containerPort: 8080
      env:
        - name: PORT
          value: "8080"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
